services:
  database:
    env_file:
      - .env
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command:
      - '--default-authentication-plugin=caching_sha2_password'
      - '--sql_mode='
      - '--max_allowed_packet=1073741824'
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-psymfony", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 30
    ports:
      - '${MYSQL_PORT}:3306'

  php_backend:
    env_file:
      - .env
    build:
      target: php_dev
      context: ${ROOT_FOLTER}/${BACKEND_FOLDER}
    depends_on:
      database:
        condition: service_healthy
    environment:
      XDEBUG_MODE: "off"
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        client_port=9003
        idekey=PHPSTORM
      PHP_IDE_CONFIG: "serverName=${BACKEND_SERVER_NAME}"
      TIMEZONE: Europe/Berlin
      PS1: '[${BACKEND_SERVER_NAME}]::$$(pwd) # '
      FRONTEND_HOST: ${FRONTEND_HOST}
      USE_SSL: ${USE_SSL}
      APP_ENV: dev
    volumes:
      - php_socket:/var/run/php
      - ${ROOT_FOLTER}/${BACKEND_FOLDER}:/srv/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx_backend:
    build:
      target: nginx_dev
      context: ${ROOT_FOLTER}/${BACKEND_FOLDER}
    depends_on:
      - php_backend
    volumes:
      - php_socket:/var/run/php
      - ${ROOT_FOLTER}/${BACKEND_FOLDER}/public:/srv/app/public
    ports:
      - '${BACKEND_PORT}:80'

  frontend:
    build:
      target: development
      context: ${ROOT_FOLTER}/${FRONTEND_FOLDER}
    volumes:
      - ${ROOT_FOLTER}/${FRONTEND_FOLDER}:/app
    environment:
      NODE_ENV: development
      DEBUG: "vite:*"
    depends_on:
      - nginx_backend
    ports:
      - "${FRONTEND_PORT}:8080"

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  radicale:
    image: tomsquest/docker-radicale:latest
    container_name: radicale
    ports:
      - "5232:5232"
    volumes:
      - ./data/caldav/data:/data
    environment:
      - RADICALE_CONFIG=/data/config
    restart: unless-stopped

volumes:
  php_socket:
  database:
    driver: local
